package schematic.validation;

public enum InvalidSchematicCauses {

    INVALID_ROOT_NAME, 
    
    MISSING_REQUIRED_ATTRIBUTE_WIDTH,
    
    MISSING_REQUIRED_ATTRIBUTE_HEIGHT, 
    
    MISSING_REQUIRED_ATTRIBUTE_LENGTH,
    
    MISSING_REQUIRED_ATTRIBUTE_BLOCKS, 
    
    MISSING_REQUIRED_ATTRIBUTE_DATA,
    
    MISSING_REQUIRED_ATTRIBUTE_MATERIALS,
    
    IF_ONE_WORLD_EDIT_INFO_IS_PROVIDED_ALL_INFOS_SHOULD_BE_PROVIDED,
    
    TYPE_OF_WIDTH_IS_NOT_SHORT, 
    
    TYPE_OF_HEIGHT_IS_NOT_SHORT,
    
    TYPE_OF_LENTGH_IS_NOT_SHORT, 
    
    TYPE_OF_DATA_IS_NOT_BYTE_ARRAY,
    
    TYPE_OF_BLOCKS_IS_NOT_BYTE_ARRAY,
    
    BLOCKS_SIZE_DOES_NOT_MATCH_VOLUME_DESCRIPTION,
    
    DATA_SIZE_DOES_NOT_MATCH_VOLUME_DESCRIPTION,
    
    ONE_OR_MORE_VOLUME_ATTRIBUTES_ARE_LESS_THAN_ZERO;

}
